filter:
    excluded_paths:
        - 'tests/*'
checks:
    php:
        code_rating: true
        duplication: true
coding_style:
    php:
        spaces:
            around_operators:
                negation: true
build: true
